JSBSim APU
legoboyvdlp/A320-family pull request #116
Opened 2020-04-18 23:47 UTC by legoboyvdlp

- JSBSim APU
- Oil simulation
- Oil consumption optional
- APU fuel pump 
- DC-ess powered on master on for three minutes

Todo: check if  fire test on batteries was fixed by dc-ess, if not, fix

2020-04-18 23:57 UTC, merspieler requested changes
Fire test still broken.

Regression: APU shutdown should be delayed, when APU BLEED was used.

2020-04-19 00:05 UTC, legoboyvdlp commented
APU shutdown _is_ delayed when APU bleed is used. Or it was last night, anyway. 

Only sixty seconds now, not 120.

2020-04-19 00:11 UTC, legoboyvdlp commented
![image](https://user-images.githubusercontent.com/10434911/79674348-39c09f00-81da-11ea-9a4f-3f177a32a8da.png)

2020-04-19 14:33 UTC, merspieler approved these changes

2020-04-19 14:33 UTC, merged