Implemented MCDU AIRWAYS page
legoboyvdlp/A320-family pull request #284
Opened 2022-12-24 11:05 UTC by noteas

### Description of Changes

Dear A320-family contributors,

Merry Christmas Eve. After several days' work, I have roughly implemented MCDU AIRWAYS page, solving issues #280 and #283. However, it may still need further testing, especially in a complete flight. By the way, I added a link of a detailed guide for navdata installation on FG Wiki to README.md.

Looking forward to your early reply.

Best wishes,
noteas

### Screenshots (optional)

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [x] Please have a main Developer test my changes before merging.

2022-12-24 13:16 UTC, merspieler commented
Thank you very much.
We'll take a look at it.

I also wish you a merry xmas.

2022-12-24 13:17 UTC, merspieler commented on Nasal/MCDU/AIRWAYS.nas
> +		#}
Commented out lines needed? If not, remove before merge

2022-12-24 13:55 UTC, noteas commented on Nasal/MCDU/AIRWAYS.nas
> +		#}
Ok. Sorry for that.

2023-01-02 22:46 UTC, legoboyvdlp commented
Are we sure that DCT legs can in fact be inserted using the AIRWAYS page?

2023-01-02 22:53 UTC, merspieler commented
Afaik no, you enter the airway and your exit way point til which you follow the airway, there're no DCT legs

2023-01-03 15:40 UTC, legoboyvdlp commented
Yes, that's what I was wondering, I thought the standard practice was using NEXT WPT to insert DCT legs.

2023-01-03 20:01 UTC, merspieler commented
yep

2023-01-16 12:43 UTC, legoboyvdlp commented
Actually thinking, maybe it would be worth merging this ... even though it's not strictly correct, at least it can be used as a base, and then after FlightGear 2020.4, the airways API can be included?

@merspieler ?

2023-01-16 22:05 UTC, merspieler commented
@legoboyvdlp I'm not really familiar with that part of the code, I trust your judgment on this.
From a project side of view, both sound fine to me.

2023-02-13 06:56 UTC, merspieler commented
@legoboyvdlp this pr is still open, you did suggest merging it, what do you say?

2023-02-20 17:24 UTC, merspieler requested changes
I'm getting an error, entering the following route
`EDDM TURB6S TURBU Y107 ASVUT Q984 VOG M858 LIGUR LIGU2L LFKC`
I've first entered SID and STAR, then went `TURBU` - > `AIRWAYS` entered `Y107`. upon trying to enter ASVUT I got the following error:
```
  953.95 [ALRT]:nasal      Nasal runtime error: flightplan.indexOfWP called on leg from different flightplan
  953.95 [ALRT]:nasal        at /games/.fgfs/Aircraft/A320-family/Nasal/MCDU/AIRWAYS.nas, line 83
  953.95 [ALRT]:nasal        called from: /games/.fgfs/Aircraft/A320-family/Nasal/MCDU/MCDU.nas, line 992
  953.95 [ALRT]:nasal        called from: , line 1
```

2023-02-20 20:30 UTC, legoboyvdlp commented
As far as I'm aware the merge request is only to add DCT legs, not airways? That being said, it shouldn't result in a nasal error if you try to add an airway, it should fail with a scratchpad message (e.g. "NOT IMPLEMENTED");

The reason is because the airways API was not made functional yet in the stable versions of flightgear, also because I can't run 2020.4 on Intel hardware (it stops rendering - yes, literally) I can't make it functional.

The E-jet-family is the only one that I know of that does work at this time

2023-02-20 21:40 UTC, merspieler commented
I've got no clue, just tested it... maybe at @noteas can take a look at it.
And what if we condition the page call to the version, like we do it with that one canvas attribute for example?

2024-09-29 21:39 UTC, Octal450 commented
What is the status of this?

2025-02-04 05:20 UTC, closed without merging

2025-02-04 05:20 UTC, Octal450 commented
No status - no updates. Closing for now.